name: Deploy Docker

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: |
            ghcr.io/${{ github.repository }}:bukan-latest
      # - name: Deploy NodeJS app
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
      #     key: ${{secrets.SSH_KEY}} # Private or public key of the server
      #     username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
      #     script: |
      #       docker ps -aq | xargs docker stop | xargs docker rm
      #       docker pull ghcr.io/dsapoetra/landing-page:latest 
      #       docker run -p 80:3000 -d ghcr.io/dsapoetra/landing-page 
      #       echo 'Deployment successful to digital ocean'
